
services:
  web-server:
    image: nginx
    networks:
      - my-network

  web-client:
    image: alpine
    command: sh -c "apk add curl && curl http://web-server"
    networks:
      - my-network

networks:
  my-network:


# docker compose up
